### ISSUE TITLE
Errors with "lang" parameters other than 'en

### ISSUE THREAD

**Issue by rodolpheg** [marcocor/tagme-python#3] opened 2017-10-30 14:35 UTC
Passing a "lang" parameter other than 'en' to mentions or annotate functions return an error. Here' s what using:
`tomatoes_mentions = tagme.mentions("I definitely like ice cream better than tomatoes.",lang = 'fr')`
returns:

> WARNING:root:Tagme returned status code 400 message:
> b'<html><head><title>Apache Tomcat/7.0.52 (Ubuntu) - Error report</title><style></style> </head><body><h1>HTTP Status 400 - Unrecognized language [fr]</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Unrecognized language [fr]</u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52 (Ubuntu)</h3></body></html>'

Thanks a lot for your work on this very useful api.

**Comment by marcocor** [comment] 2017-10-30 15:22
Hi @rodolpheg, TagMe currently supports only three languages: English, Italian and German. Meaning that the only accepted values for the **lang** parameter are **en** (default), **it** and **de**.
Have a look at the documentation here: https://sobigdata.d4science.org/web/tagme/tagme-help

Since this is not a bug in the tagme interface, I am closing it.

**Closed as completed by marcocor** 2017-10-30 15:22 UTC

**Comment by rodolpheg** [comment] 2017-10-30 15:35
Alright, thanks, sorry about that.
